<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBtxvQIx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBtxvQIx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBtxvQIx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBtxvQIx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBtxvQIx\App_KernelDevDebugContainer([
    'container.build_hash' => 'BtxvQIx',
    'container.build_id' => '1530de6c',
    'container.build_time' => 1633665350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBtxvQIx');
